version: 0.2

env:
  variables:
    SOLUTION: ".\\HelloWorld\\HelloWorld.sln"
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6.2

phases:
  install: 
    commands:
      - echo "Entered in Install Phase"
      - choco install -y chocolatey
      - choco install -y nuget.commandline
  build:
    commands:
      - echo "Entered in Build Phase"
      # - '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'